### PR TITLE
Fix/25 broken command with arguments

### PR DESCRIPTION
**Pull request by JoseKilo**
Close: #25 

Skipping the argument parsing completely seems to be enough to solve this issue.

### CODE REVIEW

**Comment by JoseKilo** [comment]
The errors on Travis seem unrelated to this PR. Probably a caching issue, resetting the cache on Travis should fix it.

```
pluggy.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 3.3.0 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('pytest>=3.6'))!
```

**Comment by geowurster** [comment]
@JoseKilo Thanks!  This looks good, and I think you are correct about the Travis caching issue, but after attempting to clear the cache and rerun several times the build is still failing with the same error.

Could you push a commit that entirely removes caching from `.travis.yml`?  I just cleared the cache again so hopefully that forces a complete rebuild.

**Comment by JoseKilo** [comment]
I've tried to remove the caching config from `.travis.yml` completely, but it didn't solve the problem. Bumping the pytest required version to match pytest-cov seems to solve it (`pytest>=3.6`).
So I've have re-enabled caching after that.

**Comment by JoseKilo** [comment]
Hi @geowurster , do you think we can merge this now ?

**Comment by geowurster** [comment]
@JoseKilo Done.  Released as version [`1.1.1`](https://pypi.org/project/click-plugins/).

**Comment by JoseKilo** [comment]
Thanks! :+1:

**Pull request merged**
